#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -s /etc/default/iodine ] ; then
	. /etc/default/iodine
	if [ -n "$START_IODINED" ] ; then
		db_set iodine/start_daemon "$START_IODINED"
	fi
	if [ -n "$IODINED_ARGS" ] ; then
		db_set iodine/daemon_options "$DAEMON_IODINED_ARGS"
	fi
fi

db_input medium iodine/start_daemon || true
db_go

db_get iodine/start_daemon
START_DAEMON=$RET

if [ "x$START_DAEMON" = "xtrue" ] ; then
	db_input medium iodine/daemon_options || true
	db_go
fi
