#!/bin/sh

CONFIGFILE=/etc/default/iodine
set -e
. /usr/share/debconf/confmodule

if [ -s $CONFIGFILE ] ; then
	. $CONFIGFILE
	db_set iodine/start_daemon    "$START_IODINED"
	db_set iodine/daemon_options  "$IODINED_ARGS"
	db_set iodine/daemon_password "$IODINED_PASSWORD"
fi

db_input medium iodine/start_daemon || true
db_go || true

db_get iodine/start_daemon
START_DAEMON=$RET

if [ "x$START_DAEMON" = "xtrue" ] ; then
	db_input medium iodine/daemon_options || true
	db_input medium iodine/daemon_password || true
	db_go || true
fi
